spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootadmin
    data: classpath:import.sql
    continue-on-error: true
  boot:
    admin:
      client:
        url: http://localhost:8089
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
server:
  port: 8080
zk:
  homepage: page/index
  springboot-packaging: war