spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootadmin
    continue-on-error: true
  resources:
    static-locations: classpath:/static/
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8089
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
  mvc:
    static-path-pattern: /**
server:
  port: 8090